CREATE TABLE review_item (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    attempt_question_id UUID NOT NULL REFERENCES assessment_attempt_question(id) ON DELETE CASCADE,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    interval_days INTEGER NOT NULL DEFAULT 1,
    repetition_count INTEGER NOT NULL DEFAULT 0,
    last_rating VARCHAR(20),
    last_reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_review_interval CHECK (interval_days BETWEEN 1 AND 365),
    CONSTRAINT chk_review_repetition CHECK (repetition_count BETWEEN 0 AND 1000),
    CONSTRAINT chk_review_rating CHECK (
        last_rating IS NULL OR last_rating IN ('FORGOT', 'DIFFICULT', 'REMEMBERED', 'EASY')
    ),
    CONSTRAINT uk_review_user_question UNIQUE (user_id, attempt_question_id)
);

CREATE INDEX idx_review_item_user_due ON review_item (user_id, due_at);

CREATE TABLE coding_interview_prompt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    title VARCHAR(180) NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    topic VARCHAR(120) NOT NULL,
    prompt TEXT NOT NULL,
    constraints_text TEXT NOT NULL,
    examples_text TEXT NOT NULL,
    expected_approach TEXT NOT NULL,
    expected_time_complexity VARCHAR(120) NOT NULL,
    expected_space_complexity VARCHAR(120) NOT NULL,
    learning_order INTEGER NOT NULL,
    CONSTRAINT chk_coding_prompt_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT uk_coding_prompt_learning_order UNIQUE (learning_order)
);

CREATE TABLE coding_interview_session (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    prompt_id BIGINT NOT NULL REFERENCES coding_interview_prompt(id),
    status VARCHAR(20) NOT NULL,
    language VARCHAR(20) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE,
    solution_code TEXT NOT NULL DEFAULT '',
    approach_notes TEXT NOT NULL DEFAULT '',
    complexity_analysis TEXT NOT NULL DEFAULT '',
    test_cases TEXT NOT NULL DEFAULT '',
    rubric_clarification INTEGER,
    rubric_approach INTEGER,
    rubric_correctness INTEGER,
    rubric_code_quality INTEGER,
    rubric_testing INTEGER,
    rubric_communication INTEGER,
    reflection TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_coding_session_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'TIMED_OUT')),
    CONSTRAINT chk_coding_session_language CHECK (language IN ('JAVA', 'PYTHON', 'CPP', 'JAVASCRIPT')),
    CONSTRAINT chk_rubric_clarification CHECK (rubric_clarification IS NULL OR rubric_clarification BETWEEN 1 AND 5),
    CONSTRAINT chk_rubric_approach CHECK (rubric_approach IS NULL OR rubric_approach BETWEEN 1 AND 5),
    CONSTRAINT chk_rubric_correctness CHECK (rubric_correctness IS NULL OR rubric_correctness BETWEEN 1 AND 5),
    CONSTRAINT chk_rubric_code_quality CHECK (rubric_code_quality IS NULL OR rubric_code_quality BETWEEN 1 AND 5),
    CONSTRAINT chk_rubric_testing CHECK (rubric_testing IS NULL OR rubric_testing BETWEEN 1 AND 5),
    CONSTRAINT chk_rubric_communication CHECK (rubric_communication IS NULL OR rubric_communication BETWEEN 1 AND 5)
);

CREATE INDEX idx_coding_session_user_started
    ON coding_interview_session (user_id, started_at DESC);
