CREATE TABLE app_user (
    id UUID PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE otp_challenge (
    id UUID PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    code_hash VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_otp_challenge_email_created
    ON otp_challenge (email, created_at DESC);

CREATE TABLE auth_session (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_auth_session_user ON auth_session (user_id);

CREATE TABLE problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leetcode_id INTEGER NOT NULL,
    slug VARCHAR(180) NOT NULL,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    topic VARCHAR(120) NOT NULL,
    CONSTRAINT chk_problem_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT uk_problem_leetcode_topic UNIQUE (leetcode_id, topic)
);

CREATE INDEX idx_problem_title ON problem (title);
CREATE INDEX idx_problem_topic ON problem (topic);
CREATE INDEX idx_problem_difficulty ON problem (difficulty);

CREATE TABLE user_progress (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    problem_id BIGINT NOT NULL REFERENCES problem(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    solved_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_progress_status CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'SOLVED')),
    CONSTRAINT uk_user_problem_progress UNIQUE (user_id, problem_id)
);

CREATE INDEX idx_user_progress_user_status ON user_progress (user_id, status);
