CREATE TABLE assessment_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(40) NOT NULL,
    source_number INTEGER NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    prompt TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option INTEGER NOT NULL,
    justification TEXT NOT NULL,
    CONSTRAINT chk_assessment_question_topic CHECK (
        topic IN ('OOPS', 'JAVA', 'SPRING_BOOT', 'REACT', 'CPP', 'PYTHON', 'COMPUTER_NETWORKS')
    ),
    CONSTRAINT chk_assessment_question_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT chk_assessment_question_correct_option CHECK (correct_option BETWEEN 0 AND 3),
    CONSTRAINT uk_assessment_question_topic_source UNIQUE (topic, source_number)
);

CREATE INDEX idx_assessment_question_topic_difficulty
    ON assessment_question (topic, difficulty);

CREATE TABLE assessment_attempt (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    topic VARCHAR(40) NOT NULL,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE,
    score INTEGER,
    CONSTRAINT chk_assessment_attempt_topic CHECK (
        topic IN ('OOPS', 'JAVA', 'SPRING_BOOT', 'REACT', 'CPP', 'PYTHON', 'COMPUTER_NETWORKS')
    ),
    CONSTRAINT chk_assessment_attempt_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'TIMED_OUT')),
    CONSTRAINT chk_assessment_attempt_number CHECK (attempt_number BETWEEN 1 AND 5),
    CONSTRAINT chk_assessment_attempt_score CHECK (score IS NULL OR score BETWEEN 0 AND 20),
    CONSTRAINT uk_assessment_attempt_user_topic_number UNIQUE (user_id, topic, attempt_number)
);

CREATE INDEX idx_assessment_attempt_user_topic
    ON assessment_attempt (user_id, topic, started_at DESC);

CREATE TABLE assessment_attempt_question (
    id UUID PRIMARY KEY,
    attempt_id UUID NOT NULL REFERENCES assessment_attempt(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES assessment_question(id),
    position INTEGER NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    prompt TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option INTEGER NOT NULL,
    justification TEXT NOT NULL,
    selected_option INTEGER,
    answered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_attempt_question_position CHECK (position BETWEEN 1 AND 20),
    CONSTRAINT chk_attempt_question_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT chk_attempt_question_correct_option CHECK (correct_option BETWEEN 0 AND 3),
    CONSTRAINT chk_attempt_question_selected_option CHECK (selected_option IS NULL OR selected_option BETWEEN 0 AND 3),
    CONSTRAINT uk_attempt_question_bank UNIQUE (attempt_id, question_id),
    CONSTRAINT uk_attempt_question_position UNIQUE (attempt_id, position)
);

CREATE INDEX idx_attempt_question_attempt
    ON assessment_attempt_question (attempt_id, position);
